// ADD_ITEM_TO_CART 
// REMOVE_ITEM_FROM_CART
// CLEAR_ITEM_CLEAR

//SHIPPING ADDRESS 
//CART_SAVE_SHIPPING_ADDRESS
//SAVE_PAYMENT_METHOD 

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD';
export const TOGGLE_CART_VISIBILITY = 'TOGGLE_CART_VISIBILITY';


