
export const USER_LOGIN_REQ = "USER_LOGIN_REQ"
export const USER_LOGIN_REQ_SUCCESS = "USER_LOGIN_REQ_SUCCESS"
export const USER_LOGIN_REQ_FAIL = "USER_LOGIN_REQ_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQ = "USER_REGISTER_REQ"
export const USER_REGISTER_REQ_SUCCESS = "USER_REGISTER_REQ_SUCCESS"
export const USER_REGISTER_REQ_FAIL = "USER_REGISTER_REQ_FAIL"

//USER_DETAILS_REQ
//USER_DETAILS_REQ_SUCCESS
//USER_DETAILS_REQ_FAIL
//USER_UPDATE_PROFILE_REQ
//USER_UPDATE_PROFILE_REQ_SUCCESS
//USER_UPDATE_PROFILE_REQ_FAIL
//USER_DETAILS_RESET
